platform :ios, '8.0'
target 'Message' do
    pod 'gobelieve', :path => './dev.podspec'
    pod 'JSBadgeView'
    pod 'leveldb-library', '~> 1.18.2'
    pod 'ZBarSDK'
    pod 'AFNetworking', '~> 3.0'
end
