platform :ios, '8.0'
target 'Message' do
    pod 'gobelieve', :path => './dev.podspec'
    pod 'JSBadgeView'
    pod 'leveldb-library', '~> 1.18.2'
    pod 'ZBarSDK'
    pod 'AFNetworking', '~> 3.0'
end

post_install do |installer|
    copy_pods_resources_path = "Pods/Target Support Files/Pods-Message/Pods-Message-resources.sh"
    string_to_replace = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"'
    assets_compile_with_app_icon_arguments = '--compile "${BUILT_PRODUCTS_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}" --app-icon "${ASSETCATALOG_COMPILER_APPICON_NAME}" --output-partial-info-plist "${BUILD_DIR}/assetcatalog_generated_info.plist"'
    text = File.read(copy_pods_resources_path)
    new_contents = text.gsub(string_to_replace, assets_compile_with_app_icon_arguments)
    File.open(copy_pods_resources_path, "w") {|file| file.puts new_contents }
end
